name: CI
 
on: 
  [push, pull_request] 
 
env:  
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.) 
  BUILD_TYPE: Release 
 
jobs: 
  build: 
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac. 
    # You can convert this to a matrix build if you need cross-platform coverage. 
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix 
    runs-on: ubuntu-latest 
 
    steps: 
    - uses: actions/checkout@v3 
 
    - uses: actions/checkout@v3 

    - name: Install clang-tidy
      working-directory: ${{github.workspace}} 
      shell: bash          
      run: sudo apt install clang-tidy

    - name: Install clang-format
      working-directory: ${{github.workspace}} 
      shell: bash          
      run: sudo apt install clang-tidy
 
    - name: Build and test 
      working-directory: ${{github.workspace}} 
      # Execute tests defined by the CMake configuration.   
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail 
      run: make
 
    - name: Install lcov 
      shell: bash          
      run: |          
          sudo apt-get install -y lcov 
 
    - name: Generate report 
      working-directory: ${{github.workspace}}/build 
      run: | 
        lcov -t "tests" -o coverage.info -c -d . 
        lcov --remove coverage.info -o coverage.info '/usr/include/*' 
        genhtml -o report coverage.info 
        ls -la

    - uses: actions/upload-artifact@v3