name: CI
 
on: 
  [push, pull_request] 
 
env:
  BUILD_TYPE: Debug 
 
jobs: 
  build-debug: 
    runs-on: ubuntu-latest 
    container: hareshutit/sourcetill:v2
 
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3 
 
    - name: Build
      working-directory: ${{github.workspace}} 
      run: make build-debug

    - name: Test
      working-directory: ${{github.workspace}} 
      run: make test-debug
    
    - name: Lint 
      working-directory: ${{github.workspace}} 
      run: make lint
          
    - name: Run coverage analyse
      working-directory: ${{github.workspace}}/build_debug
      run: |
          lcov -t "SourceTil" -o coverage.info -c -d /CMakeFiles/SourceTil_objs.dir/src/
          lcov --remove coverage.info -o coverage.info '/usr/include/*' 

    - name: Get coverage page
      working-directory: ${{github.workspace}}/build_debug
      run: |
          genhtml -o report coverage.info
 
    - name: Load coverage result
      uses: actions/upload-artifact@v3
      with:
        name: Coverage_debug
        path: build_debug/report/*

  build-release:
    runs-on: ubuntu-latest 
    container: hareshutit/sourcetill:v2

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      working-directory: ${{github.workspace}} 
      run: make build-release

    - name: Test
      working-directory: ${{github.workspace}} 
      run: make test-release
    
    - name: Run coverage analyse
      working-directory: ${{github.workspace}}/build_release
      run: |
          lcov -t "SourceTil" -o coverage.info -c -d /CMakeFiles/SourceTil_objs.dir/src/
          lcov --remove coverage.info -o coverage.info '/usr/include/*'

    - name: Get coverage page
      working-directory: ${{github.workspace}}/build_release
      run: |
          genhtml -o report coverage.info

    - name: Load coverage result
      uses: actions/upload-artifact@v3
      with:
        name: Coverage_release
        path: build_release/report/*
 

 
